### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by day-add** [robonrrd/csg#1]
Do you have any document or demonstration explaining how to detect and compute triangles intersection in libcsg.cpp? My spatial imagination ability is so poor.

**Comment by robonrrd** [comment]
You're looking for explanations of my triangle-triangle intersection code?  I used several resources, including:
https://members.loria.fr/SLazard/ARC-Visi3D/Pant-project/files/Line_Segment_Triangle.html
https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Publications/Papers/2006/2006_A_Fast_Triangle_to_triangle_Intersection_Test_for_Collision.pdf
as well as the paper "Fast and Robust Triangle-Triangle Overlap Test  Using Orientation Predicates", by  P. Guigue and O. Devillers from "Journal of Graphics Tools", 2003

**Comment by day-add** [comment]
> You're looking for explanations of my triangle-triangle intersection code? I used several resources, including: https://members.loria.fr/SLazard/ARC-Visi3D/Pant-project/files/Line_Segment_Triangle.html https://cgm.technion.ac.il/Computer-Graphics-Multimedia/Publications/Papers/2006/2006_A_Fast_Triangle_to_triangle_Intersection_Test_for_Collision.pdf as well as the paper "Fast and Robust Triangle-Triangle Overlap Test Using Orientation Predicates", by P. Guigue and O. Devillers from "Journal of Graphics Tools", 2003

Thanks a lot. Maybe there are something for aabbtree like this? I have trouble inserting a leaf now. What I can search on the internet is based on volume not surface area.
I really cannot understand why the surface area shoud times 2 in AABBTree::inertLeaf(). I would appreciate it if you have time to reply.
`      // Cost of creating a new parent for this node and the new leaf.
      double cost = 2.0 * combinedSurfaceArea;
      // Minimum cost of pushing the leaf further down the tree.
      double inheritanceCost = 2.0 * (combinedSurfaceArea - surfaceArea);`
